services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - DATABASE_URL=${DATABASE_URL}
      - EMAIL_SMTP_SERVER=${EMAIL_SMTP_SERVER}
      - EMAIL_SMTP_PORT=${EMAIL_SMTP_PORT}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - COLLEGE_ID=${COLLEGE_ID}
      - TOKEN_SECRET_KEY=${TOKEN_SECRET_KEY}
      - OTP_EXPIRY_MINUTES=${OTP_EXPIRY_MINUTES}
      - TOKEN_EXPIRE_MINUTES=${TOKEN_EXPIRE_MINUTES}
      - LLM_API_KEY=${LLM_API_KEY}
      - LLM_API_ENDPOINT=${LLM_API_ENDPOINT}
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
